### PR TITLE
add 30 movie review test data

### PR DESCRIPTION
**Pull request by RGBlife**

### CODE REVIEW

**Review by HaylzRandom — COMMENTED** [review]
Looks good, are we not letting the database auto create the ID for each review rather than hard coding it?

**Comment by Brums16** [comment]
Do the movie IDs match up to the ones from our test movies data

**Comment by RGBlife** [comment]
> Looks good, are we not letting the database auto create the ID for each review rather than hard coding it?

Good spot, I've removed the hard-coded ids

> Do the movie IDs match up to the ones from our test movies data

The movie IDs should now match the movies test data

**Review by HaylzRandom — APPROVED** [review]
All looks good to me! Do love the mixed opinions

**Comment by xandert93** [comment]
One issue I have is that on the front-end, I'm finding that a review will need to have the actual `user_id` swapped out for the actual user's details. I've added this user on `user.author` (semantic) below:

`  {
    id: 1,
    movie_id: 1,
    author: {
      id: 1,
      username: "some_username",
      avatar_url: "some_url",
      // other user fields omitted
    },
    title: "Great movie!",
    body: "I loved this movie. The acting was great and the story was really engaging.",
    vote_count: 10,
  }`
  
  Cheers :)

**Pull request merged**
